root -l -b -q 'getEfficiencyUpsilon.C+(1,0)'
root -l -b -q 'getEfficiencyUpsilon.C+(2,0)'
root -l -b -q 'getEfficiencyUpsilon.C+(3,0)'
root -l -b -q 'getEfficiencyUpsilon.C+(1,1)'
root -l -b -q 'getEfficiencyUpsilon.C+(2,1)'
root -l -b -q 'getEfficiencyUpsilon.C+(3,1)'
